### ISSUE TITLE
NoClassDefFoundError:org/apache/maven/graph/DefaultProjectDependencyGraph

### ISSUE THREAD

**Issue by ChristopherYohan** [sudhanwadindorkar/incremental-maven-builder#2]
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T13:49:05-06:00)
Maven home: D:\GridMind\Development\deployment\EMBEDDED
Java version: 11.0.1-redhat, vendor: Oracle Corporation
Java home: C:\Program Files\RedHat\java-11-openjdk-11.0.1-1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2016", version: "10.0", arch: "amd64", family: "windows"

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/maven/graph/DefaultProjectDependencyGraph
	at com.sdindorkar.maven.incremental.ChangedModulesCalculator.updateMavenSession(ChangedModulesCalculator.java:57)
	at com.sdindorkar.maven.incremental.SingleThreadedIncrementalBuilder.build(SingleThreadedIncrementalBuilder.java:54)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.graph.DefaultProjectDependencyGraph
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 17 more

**Comment by ChristopherYohan** [comment]
I commented below codes in ChangedModulesCalculator file and its working now

public void updateMavenSession(MavenSession session) throws Exception {
	//	session.setProjects(projectsToBuild);
	//	session.setProjectDependencyGraph(new DefaultProjectDependencyGraph(session.getAllProjects(), projectsToBuild));
	}
